export default {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

    USER_PROFILE_REQUEST: 'USER_PROFILE_REQUEST',
    USER_PROFILE_SUCCESS: 'USER_PROFILE_SUCCESS',
    USER_PROFILE_FAILURE: 'USER_PROFILE_FAILURE',

    USER_VERIFY_SUCCESS: 'USER_VERIFY_SUCCESS',
    USER_VERIFY_FAILURE: 'USER_VERIFY_FAILURE',

    USER_LIST_REQUEST: 'USER_LIST_REQUEST',
    USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
    USER_LIST_FAILURE: 'USER_LIST_FAILURE',

    SERVICE_LIST_SUCCESS: 'SERVICE_LIST_SUCCESS',
    SERVICE_LIST_FAILURE: 'SERVICE_LIST_FAILURE',

}